framework:
    messenger:
        default_bus: query.bus
        buses:
            command.bus:
                default_middleware: true
                middleware:
                    - middleware.transaction
            query.bus:
                default_middleware: true
                middleware:
                    - middleware.example


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
