index:
    path: /
    controller: App\Entrypoint\Controller\IndexController
logout:
    path: /logout
    controller: App\Entrypoint\Controller\User\UserLogoutController
    methods: [ POST ]
app_login:
    path: /login
    controller: App\Entrypoint\Controller\User\UserLoginController
    methods: [ GET ]
auth0_login_callback:
    path: /callback
    controller: App\Entrypoint\Controller\User\UserLoginController::callback

app_login_success:
    path: /app
    controller: App\Entrypoint\Controller\User\UserLoginController::success