index:
    path: /
    controller: App\Entrypoint\Controller\IndexController
logout:
    path: /logout
    controller: App\Entrypoint\Controller\User\UserLogoutController
login:
    path: /login
    controller: App\Entrypoint\Controller\User\UserLoginController
login_callback:
    path: /callback
    controller: App\Entrypoint\Controller\User\UserLoginController::callback

login_success:
    path: /app/loginSuccess
    controller: App\Entrypoint\Controller\User\UserLoginController::loginSuccess