# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    __instanceof:
        App\Shared\Domain\Command\MessageAppBusInterface:
            tags: [ { name: messenger.message_handler } ]
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
    App\Application\Query\:
        autowire: true
        autoconfigure: false
        resource: '../src/Application/Query/*Handler.php'
        tags: [ { name: messenger.message_handler } ]
    App\Application\Service\:
        autowire: true
        autoconfigure: true
        resource: '../src/Application/Service/*/*er.php'
    App\Entrypoint\Controller\:
        autowire: true
        autoconfigure: true
        resource: '../src/Entrypoint/Controller'
        tags: ['controller.service_arguments']
    App\Infrastructure\:
        autoconfigure: true
        autowire: true
        public: true
        resource: '../src/Infrastructure'
    App\Shared\Infrastructure\:
        autowire: true
        autoconfigure: true
        public: true
        resource: '../src/Shared/Infrastructure'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
